Tennis339/ViewModels/ScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tennis339.Models;

namespace Tennis339.ViewModels
{
    public class ScheduleViewModel
    {
        public Schedule Schedule { get; set; }
        public IEnumerable<Coach> Coach { get; set; }
    }
}

Tennis339/Controllers/CoachesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tennis339.Data;
using Tennis339.Models;

namespace Tennis339.Controllers
{
    public class CoachesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CoachesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Coaches
        public async Task<IActionResult> Index()
        {
            return View(await _context.Coach.ToListAsync());
        }

        // GET: Coaches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coach.FirstOrDefaultAsync(m => m.Id == id);

            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        // GET: Coaches/Create
        [Authorize(Policy = "RequiresCoach")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Coaches/Create
        [Authorize(Policy = "RequiresCoach")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Email,Biography,PhotoUrl")] Coach coach)
        {
            if (ModelState.IsValid)
            {
                _context.Add(coach);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coach);
        }

        // GET: Coaches/Edit/5
        [Authorize(Policy = "RequiresCoach")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coach.FindAsync(id);
            if (coach == null)
            {
                return NotFound();
            }
            return View(coach);
        }

        // POST: Coaches/Edit/5
        [Authorize(Policy = "RequiresCoach")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,Biography,PhotoUrl")] Coach coach)
        {
            if (id != coach.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coach);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoachExists(coach.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coach);
        }

        // GET: Coaches/Delete/5
        [Authorize(Policy = "RequiresCoach")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coach.FirstOrDefaultAsync(m => m.Id == id);

            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        // POST: Coaches/Delete/5
        [ActionName("Delete")]
        [Authorize(Policy = "RequiresCoach")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coach = await _context.Coach.FindAsync(id);
            _context.Coach.Remove(coach);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET Coaches/MySchedules/
        [Authorize(Policy = "RequiresCoach")]
        public IActionResult MySchedules()
        {
            // GET current User
            var user = _userManager.GetUserName(User);

            // Query db to match all records with same CoachEmail
            var schedules = _context.Schedule.Where(m => m.CoachEmail == user);

            return View("MySchedules", schedules);
        }

        // GET Coaches/Schedules/5
        [Authorize(Policy = "RequiresCoach")]
        public IActionResult Schedules(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            // Query db to find matching ID based on GET Id
            var member = _context.ScheduleMembers.Where(m => m.ScheduleId == id);

            return View("Schedules", member);
        }

        private bool CoachExists(int id)
        {
            return _context.Coach.Any(e => e.Id == id);
        }
    }
}

Tennis339/Controllers/ScheduleMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tennis339.Data;
using Tennis339.Models;

namespace Tennis339.Controllers
{
    public class ScheduleMembersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ScheduleMembersController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ScheduleMembers
        [Authorize(Policy = "RequiresAdmin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.ScheduleMembers.ToListAsync());
        }

        // GET: ScheduleMembers/Details/5
        [Authorize(Policy = "RequiresAdmin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleMembers = await _context.ScheduleMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scheduleMembers == null)
            {
                return NotFound();
            }

            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Create
        [Authorize(Policy = "RequiresAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: ScheduleMembers/Create
        [Authorize(Policy = "RequiresAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ScheduleId,MemberEmail")] ScheduleMembers scheduleMembers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(scheduleMembers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Edit/5
        [Authorize(Policy = "RequiresAdmin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleMembers = await _context.ScheduleMembers.FindAsync(id);
            if (scheduleMembers == null)
            {
                return NotFound();
            }
            return View(scheduleMembers);
        }

        // POST: ScheduleMembers/Edit/5
        [Authorize(Policy = "RequiresAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ScheduleId,MemberEmail")] ScheduleMembers scheduleMembers)
        {
            if (id != scheduleMembers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scheduleMembers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleMembersExists(scheduleMembers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scheduleMembers);
        }

        // GET: ScheduleMembers/Delete/5
        [Authorize(Policy = "RequiresMember")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scheduleMembers = await _context.ScheduleMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scheduleMembers == null)
            {
                return NotFound();
            }

            return View(scheduleMembers);
        }

        // POST: ScheduleMembers/Delete/5
        [ActionName("Delete")]
        [Authorize(Policy = "RequiresMember")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var scheduleMembers = await _context.ScheduleMembers.FindAsync(id);
            _context.ScheduleMembers.Remove(scheduleMembers);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Schedules");
        }

        // GET /ScheduleMembers/Enrollments/5
        [Authorize(Policy = "RequiresMember")]
        public IActionResult MyEnrollments()
        {
            // GET Username
            var user = _userManager.GetUserName(User);

            // Query db records that match Username
            var schedules = _context.ScheduleMembers.Where(m => m.MemberEmail == user);

            return View("MyEnrollments", schedules);
        }

        private bool ScheduleMembersExists(int id)
        {
            return _context.ScheduleMembers.Any(e => e.Id == id);
        }
    }
}

Tennis339/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tennis339.Data;
using Tennis339.Models;

namespace Tennis339.Controllers
{
    public class SchedulesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public SchedulesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Schedules
        public async Task<IActionResult> Index(string searchString)
        {
            var coaches = from m in _context.Schedule
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                coaches = coaches.Where(m => m.CoachEmail.Contains(searchString));
            }

            return View(await coaches.ToListAsync());
        }

        // GET: Schedules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule.FirstOrDefaultAsync(m => m.Id == id);

            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // GET: Schedules/Create
        [Authorize(Policy = "RequiresCoach")]
        public IActionResult Create()
        {
            // Create an instance of the 'Coach' db and store as a list
            IEnumerable<Coach> model = _context.Coach.ToList();

            // Create an instance of the view model
            ViewModels.ScheduleViewModel viewModel = new ViewModels.ScheduleViewModel
            {
                Coach = model
            };

            // Return multiple models to 'Create.cshtml' view
            return View(viewModel);
        }

        // POST: Schedules/Create
        [Authorize(Policy = "RequiresCoach")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,When,Description,CoachEmail,Location")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                _context.Add(schedule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schedule);
        }

        // GET: Schedules/Edit/5
        [Authorize(Policy = "RequiresCoach")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule.FindAsync(id);

            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // POST: Schedules/Edit/5
        [Authorize(Policy = "RequiresCoach")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,When,Description,CoachEmail,Location")] Schedule schedule)
        {
            if (id != schedule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schedule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleExists(schedule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(schedule);
        }

        // GET: Schedules/Delete/5
        [Authorize(Policy = "RequiresCoach")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule.FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [ActionName("Delete")]
        [Authorize(Policy = "RequiresCoach")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schedule = await _context.Schedule.FindAsync(id);
            _context.Schedule.Remove(schedule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Schedules/Enroll/5
        public async Task<IActionResult> Enroll(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // GET: id
            var schedule = await _context.Schedule.FirstOrDefaultAsync(m => m.Id == id);

            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // POST: Schedules/Enroll
        [ActionName("Enroll")]
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EnrollConfirmed(Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                if (schedule.When < DateTime.Now)
                {
                    // Prevent enrollment after due date
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var user = _userManager.GetUserName(User);

                    // Create a new database record
                    ScheduleMembers member = new ScheduleMembers
                    {
                        ScheduleId = schedule.Id,
                        MemberEmail = user
                    };

                    // Add a new Context change
                    _context.Add(member);

                    // Store the Enrollment
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduleExists(int id)
        {
            return _context.Schedule.Any(e => e.Id == id);
        }
    }
}

Tennis339/Views/Coaches/Create.cshtml
@model Tennis339.Models.Coach

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Coach</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Biography" class="control-label"></label>
                <input asp-for="Biography" class="form-control" />
                <span asp-validation-for="Biography" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoUrl" class="control-label"></label>
                <input asp-for="PhotoUrl" class="form-control" />
                <span asp-validation-for="PhotoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tennis339/Views/Coaches/Delete.cshtml
@model Tennis339.Models.Coach

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biography)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biography)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhotoUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Tennis339/Views/Coaches/Details.cshtml
@model Tennis339.Models.Coach

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Coach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biography)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biography)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>
        <dd>
            <img alt="Coach Image" src="@Html.DisplayFor(model => model.PhotoUrl)" />
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Admin") || User.Identity.Name == Model.Email && User.IsInRole("Coach"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-default">Edit</a>
    }
    <a asp-action="Index">Back to List</a>
</div>

Tennis339/Views/Coaches/Edit.cshtml
@model Tennis339.Models.Coach

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Coach</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" readonly />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Biography" class="control-label"></label>
                <input asp-for="Biography" class="form-control" />
                <span asp-validation-for="Biography" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoUrl" class="control-label"></label>
                <input asp-for="PhotoUrl" class="form-control" />
                <span asp-validation-for="PhotoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tennis339/Views/Coaches/Index.cshtml
@model IEnumerable<Tennis339.Models.Coach>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Coaches</h2>

@if (User.IsInRole("Admin") || User.IsInRole("Coach"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<div class="grid-thing">
    @foreach (var item in Model)
    {
        <div class="card border-dark mb-3" style="max-width: 20rem;">
            <div class="card-header">@Html.DisplayFor(modelItem => item.Email)</div>
            <div class="card-body">
                <h4 class="card-title"><img alt="Coach Image" src="@item.PhotoUrl" /></h4>
                <p class="card-text">@Html.DisplayFor(modelItem => item.Biography)</p>

                @if (User.IsInRole("Admin") || User.IsInRole("Coach") && User.Identity.Name == item.Email)
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a><span> |</span>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a><span> |</span>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
                else
                {
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                }
            </div>
        </div>
    }
</div>

Tennis339/Views/Coaches/MySchedules.cshtml
@model IEnumerable<Tennis339.Models.Schedule>

@{
    ViewData["Title"] = "My Schedules";
}

<div class="container">
    <h1>Upcoming Schedules</h1>
    @foreach (var item in Model)
    {
        <h2>@Html.DisplayFor(modelItem => item.Description)</h2>
        <a asp-controller="Coaches" asp-action="Schedules" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.When)</a><hr />
    }
    <a asp-controller="Schedules" asp-action="Create" class="btn btn-success">New Post</a>
</div>

Tennis339/Views/Coaches/Schedules.cshtml
@model IEnumerable<Tennis339.Models.ScheduleMembers>

@{
    ViewData["title"] = "Schedules";
}

<h1>Members Enrolled in this Schedule:</h1>
<hr />

@foreach (var item in Model)
{
    <h4>
        <a asp-controller="ScheduleMembers" asp-action="Details" asp-route-id="@item.Id">
            @Html.DisplayFor(modelItem => item.MemberEmail)
        </a>
    </h4>
}
<a asp-action="MySchedules" class="btn btn-default">Go back</a>